# Generated by Django 4.0.4 on 2022-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('feedText', models.TextField()),
                ('category', models.CharField(choices=[('DS', 'Dessert'), ('BV', 'Beverage'), ('AC', 'Alcohol'), ('SD', 'SideDish'), ('MK', 'MealKit'), ('AP', 'ALP')], max_length=2)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='menu/')),
            ],
        ),
    ]
